$modelname	"props_autumnal/autumnal_window001c.mdl"
$body mybody	"autumnal_window001c.smd"
$staticprop
$surfaceprop	wood
$cdmaterials	"autumnal/props"
$texturegroup "Skins"
{
	{ "maplewoodbeam001a"}
	{ "maplewoodbeam001b"}
	{ "maplewoodbeam001c"}
	{ "maplewoodbeam001d"}
	{ "maplewoodbeam001e"}
	{ "wood_beam01"}
	{ "wood_beam02"}
	{ "wood_beam03"}
}

$sequence idle	"autumnal_window001b.smd" // no animation wanted, so re-using the reference mesh